GET http://localhost:3000/

###

GET http://localhost:3000/user/getUsers

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"Rahul",
    "password":"password"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"Rahul",
    "password":"password"
}