GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.UmFodWw.fXT8YcmRdCKaAtFGfvyfz8VVq1bcNXzWjOY-980G7So
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "user":"Rahul"
}